<p>在应用程序中，公认的做法是记录一个 <code>Exception</code> ，然后重新抛出它，最终得到的日志长达数英里，其中包含同一个异常的多个实例。
在多线程应用程序中，调试这种类型的日志可能特别麻烦，因为来自其他线程的消息将与多次登录并抛出的 <code>Exception</code>交织在一起。
相反，应该记录或重新抛出异常，而不是同时记录和重新抛出异常。</p>
<h2>不合规的代码示例</h2>
<pre>
catch (SQLException e) {
  ...
  LOGGER.log(Level.ERROR,  contextInfo, e);
  throw new MySQLException(contextInfo, e);
}
</pre>
<h2>合规的解决方案</h2>
<pre>
catch (SQLException e) {
  ...
  throw new MySQLException(contextInfo, e);
}
</pre>
<p>或</p>
<pre>
catch (SQLException e) {
  ...
  LOGGER.log(Level.ERROR,  contextInfo, e);
  // handle exception...
}
</pre>

