<p>JUnit断言（assertion）不应该形成自 <code>Runnable</code> 的 <code>run</code> 方法，因为失败的断言会导致抛出
<code>AssertionError</code>。 如果从运行测试的线程以外的线程抛出错误，则线程将退出，但测试不会失败。</p>
<h2>不合规的代码示例</h2>
<pre>
public void run() {
  // ...
  Assert.assertEquals(expected, actual);  // 不合规
}
</pre>

